name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildPush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker build . --file Dockerfile --tag $DOCKER_USER/kubetest:$GITHUB_REF_NAME-$GITHUB_SHA
    
    - name: Login to Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u=$DOCKER_USER -p=$DOCKER_PASS
      
    - name: Push to Docker
      run: docker push kubetest:$GITHUB_REF_NAME-$GITHUB_SHA
